### ISSUE TITLE
Retrieve Response Cookies

### ISSUE THREAD

**Issue by rajkumardongre** [interkosmos/fortran-curl#7]
Hello @interkosmos,
How can I receive **response cookies** in an HTTP request? I know that one way to do this is to search for cookies in the **response headers**, specifically in the `Set-Cookie header`.

I have found that in curl, we can use the `curl_easy_getinfo` function with the `CURLINFO_COOKIELIST` option to retrieve cookie information. However, I am encountering an error while using this approach. Can you please provide an **example** demonstrating how to receive cookies using the `CURLINFO_COOKIELIST` option? Alternatively, if you know of any better approach, please let me know.

**Comment by interkosmos** [comment]
I added the `curl_slist` derived type with the last commit. In theory, it should work now (untested).

To write received cookies to file `/tmp/cookies.txt`:

```fortran
rc = curl_easy_setopt(curl_ptr, CURLOPT_COOKIEJAR, '/tmp/cookies.txt' // c_null_char)
```

Sending cookies to a host:

```fortran
character                     :: sep
character(len=:), allocatable :: cookies

sep = achar(9) ! tab
cookies = 'example.com'  // & ! hostname
          sep // 'FALSE' // & ! include subdomains
          sep // '/'     // & ! path
          sep // 'FALSE' // & ! secure
          sep // '0'     // & ! expiry in epoch time format, 0 = session
          sep // 'foo'   // & ! cookie name
          sep // 'value' // & ! cookie value

rc = curl_easy_setopt(curl, CURLOPT_COOKIELIST, cookies // c_null_char)
```

Reading received cookies may look like this:

```fortran
character(len=:), allocatable :: data
type(curl_slist), pointer     :: each
type(c_ptr)                   :: curl_ptr, list_ptr

! Enable cookie enginge.
rc = curl_easy_setopt(curl_ptr, CURLOPT_COOKIEFILE, c_null_char)

! Send request.
rc = curl_easy_perform(curl_ptr)

! Get cookie list.
rc = curl_easy_getinfo(curl_ptr, CURLINFO_COOKIELIST, list_ptr)

if (c_associated(list_ptr)) then
    call c_f_pointer(list_ptr, each)

    do
        if (.not. associated(each)) exit
        call c_f_str_ptr(each%data, data)
        print *, data
        call c_f_pointer(each%next, each)
    end do
end if

call curl_slist_free_all(list_ptr)
call curl_easy_cleanup(curl_ptr)
```

**Comment by rajkumardongre** [comment]
Thankyou @interkosmos, I will try this 👍
