### ISSUE TITLE
Missing implementation of libcurl MIME interfaces in fortran-curl

### ISSUE THREAD

**Issue by rajkumardongre** [interkosmos/fortran-curl#8]
Hi @interkosmos ,I noticed that the fortran-curl library does not currently implement the ISO C binding interfaces for libcurl's MIME feature. This means that users of fortran-curl are unable to send multipart form data.

Could you please consider adding support for these interfaces so that users can take advantage of this important feature? It would be great to have this functionality available in future releases of fortran-curl.

Thank you for your attention to this matter.

**Comment by interkosmos** [comment]
MIME interfaces have been added with the last commit.

**Comment by rajkumardongre** [comment]
Thanks, @interkosmos, for the commit, I will check this out
